[package]
name = "wdm-client_template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
windows = { version = "0.58.0", features = ["Win32_Security", "Win32_Storage_FileSystem","Win32_System_Ioctl", "Win32_System_IO"] }
